I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 120, in script
    return
Exception: Could not find return label (u'/Users/James/Documents/GitHub/RenPyMyProject/RenPy/game/script.rpy', 1527198100, 3).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 120, in script
    return
  File "/Users/James/Desktop/renpy-6.99.14.3-sdk/renpy/ast.py", line 1448, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "/Users/James/Desktop/renpy-6.99.14.3-sdk/renpy/execution.py", line 629, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'/Users/James/Documents/GitHub/RenPyMyProject/RenPy/game/script.rpy', 1527198100, 3).

Darwin-15.6.0-x86_64-i386-64bit
Ren'Py 6.99.14.3.3347
RenPy 1.0
Thu May 24 17:45:35 2018
